### ISSUE TITLE
html attributes not working

### ISSUE THREAD

**Issue by jhowliu** [klippx/operator-mono-atom#5]
Hi, 

thanks for your sharing

The HTML attributes and "this" not working in my Atom. But some syntax works. (e.g. class, const)

I'm using Atom 1.23.3 with your style.less configuration.

Have any suggestion ? Thanks.

**Comment by klippx** [comment]
I tried with Atom 1.24.0 (also, all my plugins are updated), and using the provided styles.less and it seems to work for me:

<img width="755" alt="screen shot 2018-02-14 at 09 13 30" src="https://user-images.githubusercontent.com/2785359/36194535-56bb6302-116a-11e8-9ef0-5ec29d2d2652.png">

In order to figure out what the problem is: 
- Do you see any warnings anywhere?
- Any conflicting plugins that might be causing this?

**Comment by klippx** [comment]
Actually, it seems the `this` is no longer wrapped in selectable css, making it impossible to style `this`:

![Screenshot_2019-03-20_at_13_46_40](https://user-images.githubusercontent.com/2785359/54685381-f5665980-4b16-11e9-8356-401d78e9119b.jpg)
